name: OrangeFox for hlte

on:
  workflow_dispatch:

jobs:
  build:
    name: OrangeFox Build Workflow
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4.1.5
      - name: Installing JDK 7 + Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gperf gcc-multilib g++-multilib libc6-dev lib32ncurses6 x11proto-core-dev libx11-dev tree lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache libreadline-dev liblz4-tool libncurses-dev libsdl2-dev libwxgtk3.2-dev libxml2 lzop imagemagick libbz2-dev ncftp qemu-user-static libstdc++-12-dev libncurses6 axel python3 python-is-python3 dos2unix build-essentials
      - name: Install OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "8"
      - name: Syncing OFRP sources
        run: |
          mkdir ~/OFRP
          cd ~/OFRP
          mkdir ~/.bin
          curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          python3 ~/.bin/repo init --depth=1 -u https://github.com/unlegacy-devices/fox-7.1_manifest -b twrp-7.1
          git clone --branch master --single-branch https://github.com/MessiInter/ofrp_device_samsung_hlte.git ~/OFRP/device/samsung/hlte
          python3 ~/.bin/repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
      - name: Building OFRP
        run: |
          OLDPATH=$PATH
          OLDJAVAHOME=$JAVA_HOME
          export PATH="$HOME/.jdk_7/java-se-7u75-ri/bin:$PATH"
          export JAVA_HOME="$HOME/.jdk_7/java-se-7u75-ri"
          cd ~/OFRP
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export LC_ALL=C
          export TARGET_ARCH=arm
          export FOX_RECOVERY_INSTALL_PARTITION="/dev/block/platform/msm_sdcc.1/by-name/recovery"
          export FOX_RECOVERY_SYSTEM_PARTITION="/dev/block/platform/msm_sdcc.1/by-name/system"
          export TW_DEFAULT_LANGUAGE="en"
          export OF_VANILLA_BUILD=1
          export OF_SKIP_ORANGEFOX_PROCESS=1
          export OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
          export OF_DONT_PATCH_ON_FRESH_INSTALLATION=1
          export OF_NO_TREBLE_COMPATIBILITY_CHECK=1
          export OF_DONT_PATCH_ENCRYPTED_DEVICE=1	
          export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
          export OF_USE_MAGISKBOOT=0
          export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=0
          export OF_USE_TWRP_SAR_DETECT=1
          export OF_FLASHLIGHT_ENABLE=0
          export OF_DEVICE_WITHOUT_PERSIST=1
          export OF_DISABLE_EXTRA_ABOUT_PAGE=1
          export FOX_DRASTIC_SIZE_REDUCTION=1
          lunch omni_hlte-eng
          make -j$(nproc --all) recoveryimage
          export PATH=$OLDPATH
          export JAVA_HOME=$OLDJAVAHOME
      - name: Uploading OFRP builds
        uses: actions/upload-artifact@v4
        with:
          name: ofrp
          path: |
            /home/runner/OFRP/out/target/product/hlte/recovery.*
            /home/runner/OFRP/out/target/product/hlte/OrangeFox-*.zip
